### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by Miskler** [Qumico/FirebaseAnalytics#1]
Привет! Твой плагин на сегодняшний момент единственный относительно рабочий, но я бы хотел рассказать о проблемах с которыми столкнулся:

1) В не экспортированном проекте все ровно идет попытка отправки данных в Firebase, что приводит к ошибке _(решается одной проверкой, отправлять только в случае если объект `firebase != null` - `Firebase.gd:128`)_
2) Кастомные параметры не корректно определяются _(`Firebase.gd:100` - у тебя идет попытка определения через `find()`, а нужно через `has()`)_
3) Если в logEvent() передать так же свои params - игра вылетает _(в моем конкретно случае - `Firebase.logEvent("died", {"cause": cause})`)_. Сейчас я в процессе решения этой проблемы, как только пойму в чем дело - отпишусь в комментарии.

**Comment by Miskler** [comment]
Кстати, после добавления Firebase у меня игра на 42 мб потяжелела _(78 мб -> 120 мб)_. Странная ситуация...

**Comment by Miskler** [comment]
На счёт пункта 3. Вообще очень странная конструкция. Может как то её упростить при помощи какого-нибудь интерпретатора? Чтобы значения сами подгонялись под эту структуру с её `"value"` и `"type"` или как-то выводить ошибку/задокументировать этот момент?

Хоть это не ошибка программная, но все ровно вызывает проблемы :(

**Comment by Miskler** [comment]
А еще данные поступают в консоль Firebase только один раз. Чтобы отыгранные данные получить на сервер нужно игру удалить и заного установить, тогда при запуске переустановленной игры она отправит на сервер данные за предыдущую сессию. Из-за чего это происходит?

**Comment by AlexeyPe** [comment]
@Miskler, Извиняюсь за задержку
Для Firebase.logEvent, ты не указал тип параметра - string/long/double, в твоём случае наверно string
Firebase.logEvent("died", {"cause": {"value": cause, "type": "string"}})
Не помню почему я не убрал type из аргументов..) 
Сейчас добавлю исходный код плагина android

**Comment by Miskler** [comment]
![image](https://github.com/Qumico/FirebaseAnalytics/assets/69055489/0318d636-93da-42ab-86a1-958accaead6f)
Спасибо, но в этом я уже давно разобрался. И да, хорошо бы тип убрать/сделать не обязательным (скорее лучше даже 2).
